Update joke.yml

diff --git a/.github/workflows/joke.yml b/.github/workflows/joke.yml
--- a/.github/workflows/joke.yml
+++ b/.github/workflows/joke.yml
@@ -3,7 +3,7 @@ name: Joke Updater
 on:
   schedule:
     - cron: '0 0 * * *' # Runs every day at 00:00
-  workflow_dispatch:  # Allows manual triggering
+  workflow_dispatch: # Allows manual triggering of the workflow
 
 jobs:
   update:
@@ -11,7 +11,7 @@ jobs:
 
     steps:
       - name: Install dependencies
-        run: sudo apt-get install -y jq
+        run: sudo apt-get install -y jq curl
 
       - uses: actions/checkout@v2
 
@@ -20,25 +20,28 @@ jobs:
         run: |
           JOKE_RESPONSE=$(curl -s https://v2.jokeapi.dev/joke/Programming)
           JOKE_TYPE=$(echo $JOKE_RESPONSE | jq -r '.type')
-
           if [ "$JOKE_TYPE" == "single" ]
           then
-              JOKE=$(echo $JOKE_RESPONSE | jq -r '.joke')
+              JOKE=$(echo $JOKE_RESPONSE | jq -r '.joke' | sed 's/"/\\"/g')
           else
-              JOKE=$(echo $JOKE_RESPONSE | jq -r '.setup, .delivery | join(" - ")')
+              SETUP=$(echo $JOKE_RESPONSE | jq -r '.setup' | sed 's/"/\\"/g')
+              DELIVERY=$(echo $JOKE_RESPONSE | jq -r '.delivery' | sed 's/"/\\"/g')
+              JOKE="$SETUP - $DELIVERY"
           fi
-
-          echo "JOKE=$JOKE" >> $GITHUB_ENV
-
+          echo "::set-output name=joke::$JOKE"
+        shell: bash
       - name: Update README
         run: |
-          JOKE=${{ env.JOKE }}
+          JOKE=${{ steps.fetch_joke.outputs.joke }}
           sed -i "/<!--joke-start-->/,/<!--joke-end-->/c\<!--joke-start-->\n$JOKE\n<!--joke-end-->" README.md
 
       - name: Commit and push
         run: |
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
+          git stash --include-untracked # Stash any changes
+          git pull --rebase
+          git stash pop || true # Apply stashed changes, don't fail if there's a conflict
           git add README.md
-          git commit -m "Updated Joke"
+          git diff --quiet && git diff --staged --quiet || git commit -m "Updated Joke"
           git push
